### ISSUE TITLE
Accessing posterior distribution of ICC for brms models

### ISSUE THREAD

**Issue by maxfarrell** [sjPlot/sjstats#66]
Hello and thank you for a very nice package. 

I have been attempting to fit phylogenetic multilevel models in brms ([via Paul's vignette](https://cran.r-project.org/web/packages/brms/vignettes/brms_phylogenetics.html)). In the vignette he says:

"The so called phylogenetic signal (often symbolize by λ) can be computed with the hypothesis method and is roughly λ=0.7 for this example.
``` r
hyp <- "sd_phylo__Intercept^2 / (sd_phylo__Intercept^2 + sigma^2) = 0"
(hyp <- hypothesis(model_simple, hyp, class = NULL))
plot(hyp)
```
Note that the phylogenetic signal is just a synonym of the intra-class correlation (ICC) used in the context phylogenetic analysis."

However, I am fitting non-gaussian models (i.e. poisson, negative binomial, and binomial-logit) so am using your package to get ICC estimates for phylogenetic signal. 

In June of 2018 I had some trouble installing your package, so pulled and modified just the icc.R script from this GitHub repo. At this time I was able to calculate ICC for a negative binomial model, and plot the full posterior, essentially representing uncertainty in the estimation of (the equivalent of) Pagel's Lambda (λ). 

I am now revisiting your package and have installed it via CRAN. When using the ```icc()``` function now I 'm not sure how I can access the posterior distribution of Pagel's Lambda, whereas before I was able to visualize it with ```plot(density((fit_nb_icc$icc_GROUPINGFACTOR)))``` where ```GROUPINGFACTOR``` is the name of the random effect. 

Maybe I'm missing something and the posterior is within the returned icc object, but I can't seem to find it. Any thoughts, help, or advice on converting the ICC to Pagels' Lambda would be greatly appreciated.

**Comment by strengejacke** [comment]
Not sure, did the `icc()` function really return a complete distribution? Can't remember... Anyway, due to unstable computation and unreliable results, `icc()` for brmsfit-objects is now always based on the variance decomposition. Furthermore, it is now re-implemented in the [performance-package](https://easystats.github.io/performance/reference/icc.html).

The code is based on the variance from the posterior predictive distribution (https://github.com/easystats/performance/blob/master/R/icc.R#L184).
