### ISSUE TITLE
Does version 0.17.3 support Xu (2003)'s omega squared?

### ISSUE THREAD

**Issue by ywebbvar** [sjPlot/sjstats#70]
Many thanks for the great software!

I can access Xu's omega square without specifying 'n' in the function r2() in v0.14.1. However, it is not returned in v0.17.3. 

Is it still available under the ICC() function?

**Comment by strengejacke** [comment]
The `r2()` has been revised, and soon will also work for `lme`-models like it already does for lme4-models. That said, omega-squared will no longer be available in favor of the most recent suggestions how to caluclate r-squared, by Nakagawa et al. 2017.

The underlying function is [get_variance()](https://easystats.github.io/insight/reference/get_variance.html) in the _insight_ package, which will be available in the beginning of April.

The new `r2()`-function, that simply relies on these variance-components, will be available in the [performance-package](https://easystats.github.io/performance/), to be released hopefully around April/May.

So I'm closing this issue here, omega-squared is in my opinion a poor alternative to r-squared (for mixed models), and thus it's no longer available.
