### ISSUE TITLE
sjstats::icc() doesn't seem to display ICC for random slopes

### ISSUE THREAD

**Issue by jrosen48** [sjPlot/sjstats#9]
Thanks for a great package. `sjstats::icc()` displays the ICC for random intercepts, but does not seem to display the ICC for random slopes, although [the code for the function](https://github.com/strengejacke/sjstats/blob/master/R/icc.R) does seem to pull out random slopes. I can try to add a reprex if it would be helpful but hoped to ask if there was a reason why this wasn't included first.

**Comment by strengejacke** [comment]
ICC is measured as random-intercept variance divided by total variance (i.e. rand. int. + residual variance), thus there is not ICC for random slopes. There are papers saying that ICC is even more or less useless for mixed models including random slopes:

> "The concept of intra-class correlation is based on a model with a random intercept only. No unique intra-class correlation can be calculated when a random slope is present in the model. The value of the between variance in models with a random slope and a random intercept is a combination of slope and intercept variance (and covariance). We know from the discussin of th basic RC model that the variance of the slope (and, as a consequence, the value of the covariance) is realted to the value of the explanatory variable x. Thus the intra-class correlation between individuals will be different, in models with random slopes, for individuals with different x-values. As a result the intra-class correlation is no longer uniquely defined".

(Kreft & De Leeuw's, Introducing Multilevel Modeling, 63)

See also: http://www.bristol.ac.uk/media-library/sites/cmm/migrated/documents/pvmm.pdf

The `icc()`-function indeed pulls out random slopes separately, simply because these information is needed for the `re_var()` and `get_re_var()`-functions-

**Comment by jrosen48** [comment]
That makes sense, of course - should have thought about what ICC describes. Thank you for your detailed and helpful response.
