### ISSUE TITLE
Error in icc.brmsfit(fit) : (list) object cannot be coerced to type ‘logical’

### ISSUE THREAD

**Issue by PiaKre** [sjPlot/sjstats#92]
When using icc(intercept.only) I get the error message

Error in icc.brmsfit(intercept.only) : (list) object cannot be coerced to type ‘logical’
when trying to fit an intercept only model, which should work for models fit with brms. I’m thinking a problem might be that my model has a multiple membership structure with two grouping variables but it might be something completely different.

Any advice what to do about this?

**Comment by strengejacke** [comment]
Please note that `icc()` is now re-implemented in the [performance-package](https://easystats.github.io/performance/reference/icc.html). Furthermore, since *brms* is able to fit models from many different families, the "classical" ICC is no longer available, but only the "decomposed" ICC (see above linked webpage). Please try to compute the ICC with the performance-package, and if you still encounter issues, feel free [to open an issue](https://github.com/easystats/performance/issues) in that repo.
